### ISSUE TITLE
cog build -t wizardcoder  wrong

### ISSUE THREAD

**Issue by ZengJin123** [lucataco/cog-wizardcoder-15b-v1#1]
![image](https://github.com/lucataco/cog-wizardcoder-15b-v1/assets/93858590/b3a40c20-6d01-4114-b429-62d59abf5029)
cog build -t wizardcoder
bash: cog: command not found...

**Comment by lucataco** [comment]
You need to Install cog for all replicate models:
https://github.com/replicate/cog
